### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by tlworks** [Ryozuki/HelperBot#1]
Inplement MySQL as Database option

**Comment by tlworks** [comment]
Might as well add /hb reload for the config 👍

**Comment by tlworks** [comment]
There's also this; 
https://i.gyazo.com/d74d9aff56ca92b21bb39deffaa1e1b2.png

**Comment by tlworks** [comment]
& https://i.gyazo.com/164a296c17f8e0a9d5ec7e1e2e8f56ae.png So I suggest making it only reply on certain equations

**Comment by edg-l** [comment]
The plugin no longer uses a database, so it doesn't record stats. Atleast for now.

https://github.com/Ryozuki/HelperBot/releases
